language: python
python:
  - "3.4"
  - "2.7"
addons:
  postgresql: "9.3"
before_install:
  - export PATH=/usr/lib/postgresql/9.3/bin:$PATH
  - sudo locale-gen --no-archive fr_FR.UTF-8
  - sudo mkdir -p /extra/pg/ts1 /extra/pg/ts2
  - sudo chown postgres:postgres /extra/pg/ts1 /extra/pg/ts2
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-plperl-9.3 postgresql-plpython-9.3
before_script:
  - psql -Upostgres -c "CREATE TABLESPACE ts1 LOCATION '/extra/pg/ts1'"
  - psql -Upostgres -c "CREATE TABLESPACE ts2 LOCATION '/extra/pg/ts2'"
script:
  - python setup.py test
